
[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick

[ConsoleVariables]
CommonUI.CheckKeyboardFocusAndParentage=1
CommonUI.DisallowUserFocusedWidgetForPendingFocusRecipient=1
CommonUI.FallbackToDesiredOnAutoRestoreFailure=1

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=54C58128407C5CC0DAD887912C04D22C

[/Script/GameplayAbilities.AbilitySystemGlobals]
; Dossiers scannés pour les GameplayCue Notifies (évite de scanner tout /Game)
+GameplayCueNotifyPaths=/Game/Gen
