;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.FlameLeap",DevComment="Sort : envol embrase (mobilite du mage de feu)")
+GameplayTagList=(Tag="Cooldown.Ability.FlameLeap",DevComment="Recharge de l\'envol embrase")
+GameplayTagList=(Tag="GameplayCue.FlameLeap.Impact",DevComment="Envol embrase : explosion a l\'atterrissage (burst)")
+GameplayTagList=(Tag="GameplayCue.FlameLeap.Trail",DevComment="Envol embrase : decollage + trainee de feu pendant le vol (looping)")
+GameplayTagList=(Tag="State.Leaping",DevComment="Le personnage est en plein bond (envol embrase)")

